# Generated by Django 2.2.1 on 2019-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='dica',
            field=models.TextField(blank=True, default='Sem dica'),
        ),
    ]
