# Generated by Django 2.2.1 on 2019-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventura',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
