# Generated by Django 2.2.1 on 2019-06-24 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aventura_visitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aventura',
            old_name='visitas',
            new_name='deslikes',
        ),
        migrations.AddField(
            model_name='aventura',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aventura',
            name='numeroJogadores',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message=None)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='acrobacia',
            field=models.IntegerField(default=0, verbose_name='Acrobacia'),
        ),
        migrations.AlterField(
            model_name='character',
            name='altura',
            field=models.FloatField(default=0, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='character',
            name='atletismo',
            field=models.IntegerField(default=0, verbose_name='Atletismo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='blefe',
            field=models.IntegerField(default=0, verbose_name='Blefe'),
        ),
        migrations.AlterField(
            model_name='character',
            name='cabelo',
            field=models.CharField(max_length=30, verbose_name='Cabelo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='carisma',
            field=models.IntegerField(default=0, verbose_name='Carisma'),
        ),
        migrations.AlterField(
            model_name='character',
            name='classe',
            field=models.CharField(max_length=25, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='character',
            name='constituicao',
            field=models.IntegerField(default=0, verbose_name='Constituição'),
        ),
        migrations.AlterField(
            model_name='character',
            name='deslocamento',
            field=models.IntegerField(default=2, verbose_name='Deslocamento'),
        ),
        migrations.AlterField(
            model_name='character',
            name='destreza',
            field=models.IntegerField(default=0, verbose_name='Destreza'),
        ),
        migrations.AlterField(
            model_name='character',
            name='diplomacia',
            field=models.IntegerField(default=0, verbose_name='Diplomacia'),
        ),
        migrations.AlterField(
            model_name='character',
            name='divindade',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Divindade'),
        ),
        migrations.AlterField(
            model_name='character',
            name='exploracao',
            field=models.IntegerField(default=0, verbose_name='Exploração'),
        ),
        migrations.AlterField(
            model_name='character',
            name='forca',
            field=models.IntegerField(default=0, verbose_name='Força'),
        ),
        migrations.AlterField(
            model_name='character',
            name='furtividade',
            field=models.IntegerField(default=0, verbose_name='Furtividade'),
        ),
        migrations.AlterField(
            model_name='character',
            name='historia',
            field=models.IntegerField(default=0, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='character',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='character',
            name='idiomas',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='iniciativa',
            field=models.IntegerField(default=0, verbose_name='Iniciativa'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inteligencia',
            field=models.IntegerField(default=0, verbose_name='Inteligência'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intimidacao',
            field=models.IntegerField(default=0, verbose_name='Intimidação'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intuicao',
            field=models.IntegerField(default=0, verbose_name='Intuição'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ladinagem',
            field=models.IntegerField(default=0, verbose_name='Ladinagem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='manha',
            field=models.IntegerField(default=0, verbose_name='Manha'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='character',
            name='natureza',
            field=models.IntegerField(default=0, verbose_name='Naruteza'),
        ),
        migrations.AlterField(
            model_name='character',
            name='olhos',
            field=models.CharField(max_length=20, verbose_name='Olhos'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pele',
            field=models.CharField(max_length=30, verbose_name='Pele'),
        ),
        migrations.AlterField(
            model_name='character',
            name='percepcao',
            field=models.IntegerField(default=0, verbose_name='Percepção'),
        ),
        migrations.AlterField(
            model_name='character',
            name='peso',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pontosDeVida',
            field=models.IntegerField(default=5, verbose_name='Pontos de Vida'),
        ),
        migrations.AlterField(
            model_name='character',
            name='raca',
            field=models.CharField(choices=[('HUM', 'HUMANO'), ('DRA', 'DRACONATOS'), ('ELF', 'ELFOS'), ('GNO', 'GNOMOS'), ('ANO', 'ANOES'), ('HAL', 'HALFLINGS'), ('ELA', 'ELADRIN')], default='HUMANO', max_length=15, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='character',
            name='religiao',
            field=models.IntegerField(default=0, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='character',
            name='rosto',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Rosto'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sabedoria',
            field=models.IntegerField(default=0, verbose_name='Sabedoria'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='socorro',
            field=models.IntegerField(default=0, verbose_name='Socorro'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tamanho',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tendencia',
            field=models.CharField(choices=[('LG', 'LAWFUL GOOD'), ('NG', 'NEUTRAL GOOD'), ('CG', 'CHAOTIC GOOD'), ('LN', 'LAWFUL NEUTRAL'), ('TN', 'TRUE NEUTRAL'), ('CN', 'CHAOTIC NEUTRAL'), ('LE', 'LAWFUL EVIL'), ('NE', 'NEUTRAL EVIL'), ('CE', 'CHAOTIC EVIL')], default='LG', max_length=2, verbose_name='Tendência'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tolerancia',
            field=models.IntegerField(default=0, verbose_name='Tolerância'),
        ),
        migrations.AlterField(
            model_name='respostapost',
            name='resposta',
            field=models.TextField(verbose_name='Resposta'),
        ),
    ]
